@startuml crearSesionClase
skinparam linetype polyline

rectangle #CDEBA5 ":PANEL_PROFESOR" as PanelProfesor
rectangle #CDEBA5 ":SESION_CLASE_ACTIVA" as SesionActiva
rectangle #CDEBA5 ":Collaboration CompletarGestion" as CompletarGestion

package crearSesionClase as "crearSesionClase()" {
    rectangle #629EF9 CrearSesionView
    rectangle #b5bd68 SesionClaseController
    rectangle #F2AC4E SesionClaseRepository
}

PanelProfesor --> CrearSesionView: crearSesionClase()

CrearSesionView -d-> SesionClaseController: aperturarNuevaSesion(asignaturaId, aula, duracion)
SesionClaseController --> SesionClaseRepository: registrarInicioSesion(sesion)

CrearSesionView ..> SesionActiva: <<include>> [éxito]
CrearSesionView ..> CompletarGestion: <<include>> completarGestion() [cancelación/error]

@enduml