@startuml consultarListaAlumnos
skinparam linetype polyline

rectangle #CDEBA5 ":PANEL_SECRETARIA" as PanelSecretaria
rectangle #CDEBA5 ":LISTADO_ALUMNOS_COMPLETO" as ListadoCompleto
rectangle #CDEBA5 ":Collaboration CompletarGestion" as CompletarGestion

package consultarListaAlumnos as "consultarListaAlumnos()" {
    rectangle #629EF9 ListaAlumnosView
    rectangle #b5bd68 AlumnoController
    rectangle #F2AC4E AlumnoRepository
}

PanelSecretaria --> ListaAlumnosView: consultarListaAlumnos()

ListaAlumnosView -d-> AlumnoController: obtenerListadoGlobalAlumnos()
AlumnoController --> AlumnoRepository: recuperarTodosLosAlumnos()

ListaAlumnosView ..> ListadoCompleto: <<include>> [éxito]
ListaAlumnosView ..> CompletarGestion: <<include>> completarGestion() [cancelación/error]

@enduml