@startuml consultarSolicitudDispensa
skinparam linetype polyline

rectangle #CDEBA5 ":PANEL_DIRECTOR" as PanelDirector
rectangle #CDEBA5 ":SOLICITUD_DISPENSA_REVISADA" as SolicitudRevisada
rectangle #CDEBA5 ":Collaboration CompletarGestion" as CompletarGestion

package consultarSolicitudDispensa as "consultarSolicitudDispensa()" {
    rectangle #629EF9 ConsultarDispensaView
    rectangle #b5bd68 DispensaController
    rectangle #F2AC4E SolicitudDispensaRepository
}

PanelDirector --> ConsultarDispensaView: consultarSolicitudDispensa()

ConsultarDispensaView -d-> DispensaController: listarSolicitudesPendientes()
DispensaController --> SolicitudDispensaRepository: buscarPorEstado("PENDIENTE")

ConsultarDispensaView ..> SolicitudRevisada: <<include>> [éxito]
ConsultarDispensaView ..> CompletarGestion: <<include>> completarGestion() [cancelación/error]

@enduml