@startuml editarSolicitudDispensa-analisis
skinparam linetype polyline

rectangle #CDEBA5 ":Solicitud Dispensa Abierta" as SolicitudDispensaAbierta

package editarSolicitudDispensa as "editarSolicitudDispensa()" {
    rectangle #629EF9 EditarSolicitudDispensaView
    rectangle #b5bd68 DispensaController
    rectangle #F2AC4E DispensaRepository
    rectangle #F2AC4E Dispensa
}

SolicitudDispensaAbierta -r-> EditarSolicitudDispensaView: editarSolicitudDispensa()
EditarSolicitudDispensaView -d-> DispensaController: editarSolicitudDispensa(dispensaId, datos)
DispensaController -d-> DispensaRepository: update(dispensaId, datos)
DispensaRepository -d-> Dispensa: update(datos)
Dispensa --u-> DispensaRepository
DispensaRepository --u-> DispensaController
DispensaController --u-> EditarSolicitudDispensaView
@enduml
