@startuml editarUsuario-analisis
skinparam linetype polyline

rectangle #CDEBA5 ":Panel Admin Abierto" as PanelAdminAbierto

package editarUsuario as "editarUsuario()" {
    rectangle #629EF9 EditarUsuarioView
    rectangle #b5bd68 UsuarioController
    rectangle #F2AC4E UsuarioRepository
    rectangle #F2AC4E Usuario
}

PanelAdminAbierto -r-> EditarUsuarioView: editarUsuario()

EditarUsuarioView -d-> UsuarioController: obtenerUsuario(id) : Usuario

UsuarioController --> UsuarioRepository: obtenerPorId(id) : Usuario

UsuarioRepository -- Usuario

EditarUsuarioView --> UsuarioController: validarDatos(nombre, email, rol) : boolean

UsuarioController --> UsuarioRepository: verificarUnicidad(email, id) : boolean

EditarUsuarioView --> UsuarioController: editarUsuario(id, nombre, email, rol) : Usuario

UsuarioController --> UsuarioRepository: actualizar(id, nombre, email, rol) : Usuario

@enduml
