@startuml crearSolicitudDispensa-analisis
skinparam linetype polyline

rectangle #CDEBA5 ":Dispensas Abierto" as DispensasAbierto

package crearSolicitudDispensa as "crearSolicitudDispensa()" {
    rectangle #629EF9 CrearSolicitudDispensaView
    rectangle #b5bd68 DispensaController
    rectangle #F2AC4E DispensaRepository
    rectangle #F2AC4E Dispensa
}

DispensasAbierto -r-> CrearSolicitudDispensaView: crearSolicitudDispensa()
CrearSolicitudDispensaView -d-> DispensaController: crearSolicitudDispensa(alumnoId, asignaturaId, periodo, horario, motivo)
DispensaController -d-> DispensaRepository: create(alumnoId, asignaturaId, periodo, horario, motivo)
DispensaRepository -d-> Dispensa: new(alumnoId, asignaturaId, periodo, horario, motivo)
Dispensa --u-> DispensaRepository
DispensaRepository --u-> DispensaController
DispensaController --u-> CrearSolicitudDispensaView
@enduml
