@startuml editarSolicitudDispensa
skinparam linetype polyline

rectangle #CDEBA5 ":SOLICITUD_DISPENSA_REVISADA" as SolicitudRevisada
rectangle #CDEBA5 ":SOLICITUD_DISPENSA_EVALUADA" as SolicitudEvaluada
rectangle #CDEBA5 ":Collaboration CompletarGestion" as CompletarGestion

package editarSolicitudDispensa as "editarSolicitudDispensa()" {
    rectangle #629EF9 EditarSolicitudView
    rectangle #b5bd68 DispensaController
    rectangle #F2AC4E SolicitudDispensaRepository
}

SolicitudRevisada --> EditarSolicitudView: editarSolicitud()

EditarSolicitudView -d-> DispensaController: resolverSolicitud(solicitudId, resolucion, comentario)
DispensaController --> SolicitudDispensaRepository: cambiarEstadoYResolucion(solicitud)

EditarSolicitudView ..> SolicitudEvaluada: <<include>> [éxito]
EditarSolicitudView ..> CompletarGestion: <<include>> completarGestion() [cancelación/error]

@enduml