@startuml guardarSolicitudDispensa-analisis
skinparam linetype polyline

rectangle #CDEBA5 ":Dashboard Secretaria Abierto" as DashboardSecretariaAbierto
rectangle #CDEBA5 ":Dashboard Director Abierto" as DashboardDirectorAbierto

package guardarSolicitudDispensa as "guardarSolicitudDispensa()" {
    rectangle #629EF9 GuardarSolicitudDispensaView
    rectangle #b5bd68 DispensaController
    rectangle #F2AC4E DispensaRepository
    rectangle #F2AC4E Dispensa
}

DashboardSecretariaAbierto -r-> GuardarSolicitudDispensaView: guardarSolicitudDispensa()
DashboardDirectorAbierto -r-> GuardarSolicitudDispensaView: guardarSolicitudDispensa()

GuardarSolicitudDispensaView -d-> DispensaController: obtenerDispensa(dispensaId) : Dispensa

DispensaController --> DispensaRepository: obtenerPorId(dispensaId) : Dispensa

DispensaRepository -- Dispensa

GuardarSolicitudDispensaView --> DispensaController: guardarSolicitudDispensa(dispensaId, estado) : Dispensa

DispensaController --> DispensaRepository: actualizarEstado(dispensaId, estado) : Dispensa

@enduml
