@startuml crearSesionClase-analisis
skinparam linetype polyline

rectangle #CDEBA5 ":Asistencias Abierto" as AsistenciasAbierto

package crearSesionClase as "crearSesionClase()" {
    rectangle #629EF9 CrearSesionClaseView
    rectangle #b5bd68 SesionClaseController
    rectangle #F2AC4E AsignaturaRepository
    rectangle #F2AC4E SesionClaseRepository
    rectangle #F2AC4E Asignatura
    rectangle #F2AC4E SesionDeClase
}

AsistenciasAbierto -r-> CrearSesionClaseView: crearSesionClase()
CrearSesionClaseView -d-> SesionClaseController: cargarAsignaturas(profesorId)
SesionClaseController -d-> AsignaturaRepository: obtenerPorProfesor(profesorId)
AsignaturaRepository -d-> Asignatura: findByProfesor(profesorId)
Asignatura --u-> AsignaturaRepository
AsignaturaRepository --u-> SesionClaseController
SesionClaseController -d-> SesionClaseRepository: crear(asignaturaId, fecha, aula, duracion)
SesionClaseRepository -d-> SesionDeClase: new(asignaturaId, fecha, aula, duracion)
SesionDeClase --u-> SesionClaseRepository
SesionClaseRepository --u-> SesionClaseController
SesionClaseController --u-> CrearSesionClaseView
@enduml