@startuml editarSolicitudDispensa
skinparam linetype polyline

rectangle #CDEBA5 ":HISTORIAL_DISPENSAS_MOSTRADO" as HistorialDispensas
rectangle #CDEBA5 ":DISPENSA_RECTIFICADA" as DispensaRectificada
rectangle #CDEBA5 ":Collaboration CompletarGestion" as CompletarGestion

package editarSolicitudDispensa as "editarSolicitudDispensa()" {
    rectangle #629EF9 EditarDispensaView
    rectangle #b5bd68 DispensaController
    rectangle #F2AC4E SolicitudDispensaRepository
}

HistorialDispensas --> EditarDispensaView: editarSolicitudDispensa()

EditarDispensaView -d-> DispensaController: corregirDatosDispensa(solicitudId, nuevosDatos)
DispensaController --> SolicitudDispensaRepository: actualizarDatosDispensa(solicitud)

EditarDispensaView ..> DispensaRectificada: <<include>> [éxito]
EditarDispensaView ..> CompletarGestion: <<include>> completarGestion() [cancelación/error]

@enduml