@startuml importarMatriculas-analisis
skinparam linetype polyline

rectangle #CDEBA5 ":Matriculas Abierto" as MatriculasAbierto

package importarMatriculas as "importarMatriculas()" {
    rectangle #629EF9 ImportarMatriculasView
    rectangle #b5bd68 MatriculaController
    rectangle #F2AC4E AlumnoRepository
    rectangle #F2AC4E MatriculaRepository
    rectangle #F2AC4E Alumno
    rectangle #F2AC4E Matricula
}

MatriculasAbierto -r-> ImportarMatriculasView: importarMatriculas()
ImportarMatriculasView -d-> MatriculaController: validarArchivo(archivo)
MatriculaController --u-> ImportarMatriculasView
ImportarMatriculasView -d-> MatriculaController: importarMatriculas(archivo)
MatriculaController -d-> AlumnoRepository: obtenerPorDni(dni)
AlumnoRepository -d-> Alumno: findByDni(dni)
Alumno --u-> AlumnoRepository
AlumnoRepository --u-> MatriculaController
MatriculaController -d-> MatriculaRepository: crearOActualizar(alumnoId, asignaturaId)
MatriculaRepository -d-> Matricula: new(alumnoId, asignaturaId)
Matricula --u-> MatriculaRepository
MatriculaRepository --u-> MatriculaController
MatriculaController --u-> ImportarMatriculasView
@enduml