@startuml editarSolicitudDispensa
skinparam linetype polyline

rectangle #CDEBA5 ":SOLICITUD_DISPENSA_DETALLADA" as SolicitudDetallada
rectangle #CDEBA5 ":SOLICITUD_DISPENSA_ACTUALIZADA" as SolicitudActualizada
rectangle #CDEBA5 ":Collaboration CompletarGestion" as CompletarGestion

package editarSolicitudDispensa as "editarSolicitudDispensa()" {
    rectangle #629EF9 EditarDispensaView
    rectangle #b5bd68 DispensaController
    rectangle #F2AC4E SolicitudDispensaRepository
}

SolicitudDetallada --> EditarDispensaView: editarSolicitudDispensa()

EditarDispensaView -d-> DispensaController: actualizarSolicitud(solicitudId, nuevosCampos)
DispensaController --> SolicitudDispensaRepository: actualizarDatosDispensa(solicitud)

EditarDispensaView ..> SolicitudActualizada: <<include>> [éxito]
EditarDispensaView ..> CompletarGestion: <<include>> completarGestion() [cancelación/error]

@enduml