@startuml editarSesionClase
skinparam linetype polyline

rectangle #CDEBA5 ":SESION_CLASE_ACTIVA" as SesionActiva
rectangle #CDEBA5 ":SESION_CLASE_MODIFICADA" as SesionModificada
rectangle #CDEBA5 ":Collaboration CompletarGestion" as CompletarGestion

package editarSesionClase as "editarSesionClase()" {
    rectangle #629EF9 EditarSesionView
    rectangle #b5bd68 SesionClaseController
    rectangle #F2AC4E SesionClaseRepository
}

SesionActiva --> EditarSesionView: editarSesionClase()

EditarSesionView -d-> SesionClaseController: reajustarParametrosSesion(sesionId, nuevosParametros)
SesionClaseController --> SesionClaseRepository: actualizarDatosSesion(sesion)

EditarSesionView ..> SesionModificada: <<include>> [éxito]
EditarSesionView ..> CompletarGestion: <<include>> completarGestion() [cancelación/error]

@enduml