@startuml crearSolicitudDispensa
skinparam linetype polyline

rectangle #CDEBA5 ":PANEL_SECRETARIA" as PanelSecretaria
rectangle #CDEBA5 ":DISPENSA_INSTITUCIONAL_REGISTRADA" as DispensaInstitucional
rectangle #CDEBA5 ":Collaboration CompletarGestion" as CompletarGestion

package crearSolicitudDispensa as "crearSolicitudDispensa()" {
    rectangle #629EF9 RegistrarDispensaView
    rectangle #b5bd68 DispensaController
    rectangle #F2AC4E SolicitudDispensaRepository
}

PanelSecretaria --> RegistrarDispensaView: crearSolicitudDispensa()

RegistrarDispensaView -d-> DispensaController: inyectarSolicitud DeOficio(datosDispensa)
DispensaController --> SolicitudDispensaRepository: guardarSolicitud(solicitud)

RegistrarDispensaView ..> DispensaInstitucional: <<include>> [éxito]
RegistrarDispensaView ..> CompletarGestion: <<include>> completarGestion() [cancelación/error]

@enduml