@startuml consultarListaAlumnos-analisis
skinparam linetype polyline

rectangle #CDEBA5 ":Dashboard Profesor Abierto" as DashboardProfesorAbierto
rectangle #CDEBA5 ":Dashboard Secretaria Abierto" as DashboardSecretariaAbierto

package consultarListaAlumnos as "consultarListaAlumnos()" {
    rectangle #629EF9 ConsultarListaAlumnosView
    rectangle #b5bd68 AlumnoController
    rectangle #F2AC4E MatriculaRepository
    rectangle #F2AC4E AlumnoRepository
    rectangle #F2AC4E Matricula
    rectangle #F2AC4E Alumno
}

DashboardProfesorAbierto -r-> ConsultarListaAlumnosView: consultarListaAlumnos()
DashboardSecretariaAbierto -r-> ConsultarListaAlumnosView: consultarListaAlumnos()

ConsultarListaAlumnosView -d-> AlumnoController: obtenerAlumnos(asignaturaId) : List<Alumno>

AlumnoController --> MatriculaRepository: obtenerPorAsignatura(asignaturaId) : List<Matricula>

MatriculaRepository -- Matricula

AlumnoController --> AlumnoRepository: obtenerPorIds(ids) : List<Alumno>

AlumnoRepository -- Alumno

@enduml
