@startuml exportarHistorialAsistencias
title Diagrama de Secuencia - Exportar Asistencias (Diseño)

actor "Profesor" as Teacher
participant "Frontend (React)" as FE
participant "ReporteController" as Controller
participant "ReporteService" as Service
participant "AsistenciaRepository" as Repository

Teacher -> FE: Descargar Reporte
activate FE

FE -> Controller: GET /api/reportes/asistencias/{grupoId}/exportar
activate Controller

Controller -> Service: generarReporteAsistencias(grupoId)
activate Service
Service -> Repository: getMetricasPorGrupo(grupoId)
activate Repository
Repository --> Service: List<AsistenciaProjection>
deactivate Repository
Service --> Controller: byte[] (Archivo CSV/PDF)
deactivate Service

Controller --> FE: 200 OK (Content-Disposition: attachment)
deactivate Controller
deactivate FE
@enduml