@startuml
Title Casos de Uso: Profesor
left to right direction
skinparam style strictuml

actor Profesor

package "Módulo Alumnos " {
    usecase "Consultar alumno" as AlumnosConsultar
}

package "Módulo Asistencias" {
    usecase "Crear sesión de clase" as AsistenciasCrearSesion
    usecase "Editar sesión de clase" as AsistenciasEditarSesion
    usecase "Registrar toma de asistencia" as AsistenciasRegistrarToma
    usecase "Cerrar sesión de clase" as AsistenciasCerrarSesion
    usecase "Exportar historial de asistencias" as AsistenciasExportarHistorial
}

package "Módulo Dispensas" {
    usecase "Consultar solicitud de dispensa" as DispensasConsultar
}

Profesor --> AlumnosConsultar

Profesor --> AsistenciasCrearSesion
Profesor --> AsistenciasEditarSesion
Profesor --> AsistenciasRegistrarToma
Profesor --> AsistenciasCerrarSesion
Profesor --> AsistenciasExportarHistorial

Profesor --> DispensasConsultar
@enduml