@startuml crearSolicitudDispensa
title Diagrama de Secuencia - Crear Dispensa De Oficio (Diseño)

actor "Secretaría" as AdminUser
participant "Frontend (React)" as FE
participant "DispensaController" as Controller
participant "DispensaService" as Service
participant "DispensaRepository" as Repository

AdminUser -> FE: Registrar Dispensa Institucional
activate FE

FE -> Controller: POST /api/dispensas/oficio
activate Controller

Controller -> Service: inyectarDispensa(dispensaDTO)
activate Service
Service -> Repository: save(dispensaInstitucional)
activate Repository
Repository --> Service: Dispensa
deactivate Repository
Service --> Controller: DispensaDTO
deactivate Service

Controller --> FE: 201 Created
deactivate Controller
deactivate FE
@enduml